# Site wide configuration

title: Frantisek Stanek
bio: "Geophysicist"
locale: en_US
url:
image:
  feature: fm-header-1.jpg

# Jekyll configuration

permalink:   pretty
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Frantisek Stanek
  avatar: FS_head.jpg
  bio: "Geophysicist"
  github: StanekFr
  bitbucket: #username
  orcid: 0000-0002-0037-9239
  scholar: k5i3d9MAAAAJ
  mendeley: #username
  researchgate: Frantisek-Stanek
  stackoverflow: #username
  email: FStanek@mines.edu
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google: #username
    plus: #username
    analytics: #username
    verify: #username
    ad-client: #username
    ad-slot: #username
  bing-verify: #username
  linkedin: stanekfr
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
